name: Rebase tracking branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rebase-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      #- name: Setup Git user
      #  run: |
      #    git config user.name "github-actions[bot]"
      #    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Rebase Tracking onto main
        run: |
          git checkout Tracking
          git rebase origin/main
          git push

    # ─────────── Python setup & command ───────────
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install polars matplotlib

      - uses: ConorMacBride/install-package@v1
        with:
          apt: texlive-extra-utils


        