name: Rebase tracking branch

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rebase-tracking:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - run: pip install polars matplotlib

      - run: sudo apt-get -y install texlive-extra-utils

      - run: texcount -dir -inc thesis.tex      
      - run: texcount -dir -inc thesis.tex -out=Tracking/output.texcount

      - run: python3 Tracking/analyse.py -i Tracking/output.texcount --db Tracking/progress.db

      - run: |
          git config --global user.name 'Walkersb101'
          git config --global user.email 'Walkersb10@users.noreply.github.com'
          git add .
          git commit -a -m "Update progress"
          git push



        